language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install: 
  - "pip install cookiecutter rstcheck sphinx"
  - "export GIT_HOME=`pwd`"
  - "cd .."

  - "cookiecutter cookiecutter-plumbum-cli --no-input -f"
  - "virtualenv .venv -p python3 && source .venv/bin/activate && cd COOKIECUTTER__project-name"
  - "export CC_HOME=`pwd`"
  - "travis_retry pip install -e ."
  - "deactivate"
  - "pwd"
  - "cd $GIT_HOME"
  - "pwd"
script:
  - "pwd"
  - "rstcheck ../COOKIECUTTER__project-name/README.rst"
  - "source ../.venv/bin/activate"
  - "cd $CC_HOME"
  - "python setup.py test"
  - "python setup.py sdist bdist_wheel"
  - "deactivate"
  - "sphinx-apidoc -f -o docs/source COOKIECUTTER__library_name"
  - "sphinx-build -b html docs/ webpage"

