# GENERATED: {{cookiecutter.author_name}} @ {% now 'utc' %} -- {{cookiecutter._template}}v{{cookiecutter.template_version}}
language: python
python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
install: 
  - "pip install ."
script:
  - "python setup.py test"
after_success:
  - "pip install python-coveralls"
  - "coveralls"